services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - otel-collector
      - dynamodb
    environment:
      - OTEL_SERVICE_NAME=sample-koa
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - DYNAMODBHOST=dynamodb:8000
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
  redis:
    image: "redis:alpine"
    healthcheck:
      test: "[ $$(redis-cli ping) = 'PONG' ]"
      interval: 1s
      timeout: 3s
      retries: 5
  dynamodb:
    image: "amazon/dynamodb-local"
    volumes:
      -  ./fakeMyKeyId_localhost.db:/home/dynamodblocal/data/fakeMyKeyId_localhost.db
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data/"
  zipkin:
      image: openzipkin/zipkin:latest
      restart: always
      ports:
        - "9411:9411"    
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - zipkin
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"    
